WARNING 2025-08-19 06:38:12,329 log 1696 31380 Forbidden (Permission denied): /bookshelf/books/
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\contrib\auth\decorators.py", line 56, in _view_wrapper
    test_pass = test_func(request.user)
  File "C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\django\contrib\auth\decorators.py", line 129, in check_perms
    raise PermissionDenied
django.core.exceptions.PermissionDenied
